import type { Listing, SavedSearch } from "./types";

// 18 realistic fire apparatus listings
export const INITIAL_LISTINGS: Listing[] = [
  // Pumpers (5) - including 2 Texas Pierce pumpers to match default saved search
  {
    id: "pump-001",
    title: "2018 Pierce Enforcer Pumper",
    year: 2018,
    manufacturer: "Pierce",
    category: "Fire Apparatus",
    type: "Pumper",
    price: 145000,
    mileage: 28000,
    pumpGPM: 1500,
    tankGallons: 750,
    city: "Houston",
    state: "TX",
    imageUrl: "https://placehold.co/400x300/dc2626/ffffff?text=2018+Pierce+Pumper",
    listingType: "buy_now",
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "pump-002",
    title: "2015 Pierce Arrow XT Pumper",
    year: 2015,
    manufacturer: "Pierce",
    category: "Fire Apparatus",
    type: "Pumper",
    price: 98000,
    mileage: 45000,
    pumpGPM: 1250,
    tankGallons: 1000,
    city: "Dallas",
    state: "TX",
    imageUrl: "https://placehold.co/400x300/dc2626/ffffff?text=2015+Pierce+Pumper",
    listingType: "buy_now",
    createdAt: "2024-01-10T14:30:00Z",
  },
  {
    id: "pump-003",
    title: "2012 E-One Typhoon Pumper",
    year: 2012,
    manufacturer: "E-One",
    category: "Fire Apparatus",
    type: "Pumper",
    price: 67000,
    mileage: 72000,
    pumpGPM: 1500,
    tankGallons: 750,
    city: "Phoenix",
    state: "AZ",
    imageUrl: "https://placehold.co/400x300/dc2626/ffffff?text=2012+E-One+Pumper",
    listingType: "buy_now",
    createdAt: "2024-01-08T09:15:00Z",
  },
  {
    id: "pump-004",
    title: "2020 Seagrave Marauder II Pumper",
    year: 2020,
    manufacturer: "Seagrave",
    category: "Fire Apparatus",
    type: "Pumper",
    price: 175000,
    mileage: 15000,
    pumpGPM: 2000,
    tankGallons: 500,
    city: "Chicago",
    state: "IL",
    imageUrl: "https://placehold.co/400x300/dc2626/ffffff?text=2020+Seagrave+Pumper",
    listingType: "auction",
    createdAt: "2024-01-12T11:00:00Z",
  },
  {
    id: "pump-005",
    title: "2008 KME Predator Pumper",
    year: 2008,
    manufacturer: "KME",
    category: "Fire Apparatus",
    type: "Pumper",
    price: 45000,
    mileage: 95000,
    pumpGPM: 1250,
    tankGallons: 1000,
    city: "Denver",
    state: "CO",
    imageUrl: "https://placehold.co/400x300/dc2626/ffffff?text=2008+KME+Pumper",
    listingType: "buy_now",
    createdAt: "2024-01-05T16:45:00Z",
  },

  // Tankers (3)
  {
    id: "tank-001",
    title: "2016 Freightliner/KME Tanker",
    year: 2016,
    manufacturer: "KME",
    category: "Tankers",
    type: "Tanker",
    price: 85000,
    mileage: 32000,
    pumpGPM: 500,
    tankGallons: 3000,
    city: "Nashville",
    state: "TN",
    imageUrl: "https://placehold.co/400x300/1e40af/ffffff?text=2016+KME+Tanker",
    listingType: "buy_now",
    createdAt: "2024-01-14T08:00:00Z",
  },
  {
    id: "tank-002",
    title: "2010 International/E-One Tanker",
    year: 2010,
    manufacturer: "E-One",
    category: "Tankers",
    type: "Tanker",
    price: 52000,
    mileage: 58000,
    pumpGPM: 750,
    tankGallons: 2500,
    city: "Atlanta",
    state: "GA",
    imageUrl: "https://placehold.co/400x300/1e40af/ffffff?text=2010+E-One+Tanker",
    listingType: "buy_now",
    createdAt: "2024-01-06T13:20:00Z",
  },
  {
    id: "tank-003",
    title: "2019 Pierce Kenworth Tanker",
    year: 2019,
    manufacturer: "Pierce",
    category: "Tankers",
    type: "Tanker",
    price: 95000,
    mileage: 22000,
    pumpGPM: 1000,
    tankGallons: 3000,
    city: "Sacramento",
    state: "CA",
    imageUrl: "https://placehold.co/400x300/1e40af/ffffff?text=2019+Pierce+Tanker",
    listingType: "auction",
    createdAt: "2024-01-11T10:30:00Z",
  },

  // Aerials (3)
  {
    id: "aerial-001",
    title: "2017 Pierce Ascendant 107' Aerial",
    year: 2017,
    manufacturer: "Pierce",
    category: "Fire Apparatus",
    type: "Aerial",
    price: 285000,
    mileage: 38000,
    pumpGPM: 2000,
    tankGallons: 500,
    city: "Los Angeles",
    state: "CA",
    imageUrl: "https://placehold.co/400x300/7c3aed/ffffff?text=2017+Pierce+Aerial",
    listingType: "buy_now",
    createdAt: "2024-01-13T15:00:00Z",
  },
  {
    id: "aerial-002",
    title: "2014 Sutphen 100' Platform",
    year: 2014,
    manufacturer: "Sutphen",
    category: "Fire Apparatus",
    type: "Ladder",
    price: 195000,
    mileage: 52000,
    pumpGPM: 1500,
    tankGallons: 300,
    city: "Miami",
    state: "FL",
    imageUrl: "https://placehold.co/400x300/7c3aed/ffffff?text=2014+Sutphen+Platform",
    listingType: "buy_now",
    createdAt: "2024-01-09T12:00:00Z",
  },
  {
    id: "aerial-003",
    title: "2011 E-One 75' Quint",
    year: 2011,
    manufacturer: "E-One",
    category: "Fire Apparatus",
    type: "Aerial",
    price: 155000,
    mileage: 68000,
    pumpGPM: 1500,
    tankGallons: 500,
    city: "Seattle",
    state: "WA",
    imageUrl: "https://placehold.co/400x300/7c3aed/ffffff?text=2011+E-One+Quint",
    listingType: "auction",
    createdAt: "2024-01-07T09:45:00Z",
  },

  // Ambulances (4)
  {
    id: "amb-001",
    title: "2019 Ford F-450 Type I Ambulance",
    year: 2019,
    manufacturer: "Freightliner",
    category: "Ambulances",
    type: "Ambulance",
    price: 85000,
    mileage: 45000,
    pumpGPM: null,
    tankGallons: null,
    city: "Boston",
    state: "MA",
    imageUrl: "https://placehold.co/400x300/16a34a/ffffff?text=2019+Type+I+Ambulance",
    listingType: "buy_now",
    createdAt: "2024-01-14T14:00:00Z",
  },
  {
    id: "amb-002",
    title: "2016 Chevrolet G4500 Type III Ambulance",
    year: 2016,
    manufacturer: "International",
    category: "Ambulances",
    type: "Ambulance",
    price: 52000,
    mileage: 82000,
    pumpGPM: null,
    tankGallons: null,
    city: "Portland",
    state: "OR",
    imageUrl: "https://placehold.co/400x300/16a34a/ffffff?text=2016+Type+III+Ambulance",
    listingType: "buy_now",
    createdAt: "2024-01-04T11:30:00Z",
  },
  {
    id: "amb-003",
    title: "2021 Ford E-450 Type III Ambulance",
    year: 2021,
    manufacturer: "Freightliner",
    category: "Ambulances",
    type: "Ambulance",
    price: 78000,
    mileage: 28000,
    pumpGPM: null,
    tankGallons: null,
    city: "Minneapolis",
    state: "MN",
    imageUrl: "https://placehold.co/400x300/16a34a/ffffff?text=2021+Type+III+Ambulance",
    listingType: "buy_now",
    createdAt: "2024-01-15T09:00:00Z",
  },
  {
    id: "amb-004",
    title: "2013 International 4300 Type I Ambulance",
    year: 2013,
    manufacturer: "International",
    category: "Ambulances",
    type: "Ambulance",
    price: 28000,
    mileage: 125000,
    pumpGPM: null,
    tankGallons: null,
    city: "Cleveland",
    state: "OH",
    imageUrl: "https://placehold.co/400x300/16a34a/ffffff?text=2013+Type+I+Ambulance",
    listingType: "auction",
    createdAt: "2024-01-03T16:00:00Z",
  },

  // Rescue Trucks (3)
  {
    id: "rescue-001",
    title: "2017 Pierce Heavy Rescue",
    year: 2017,
    manufacturer: "Pierce",
    category: "Rescue Trucks",
    type: "Rescue",
    price: 145000,
    mileage: 35000,
    pumpGPM: null,
    tankGallons: null,
    city: "San Diego",
    state: "CA",
    imageUrl: "https://placehold.co/400x300/ea580c/ffffff?text=2017+Pierce+Rescue",
    listingType: "buy_now",
    createdAt: "2024-01-12T08:30:00Z",
  },
  {
    id: "rescue-002",
    title: "2014 Spartan/SVI Heavy Rescue",
    year: 2014,
    manufacturer: "Spartan",
    category: "Rescue Trucks",
    type: "Rescue",
    price: 95000,
    mileage: 48000,
    pumpGPM: null,
    tankGallons: null,
    city: "Philadelphia",
    state: "PA",
    imageUrl: "https://placehold.co/400x300/ea580c/ffffff?text=2014+Spartan+Rescue",
    listingType: "buy_now",
    createdAt: "2024-01-08T14:15:00Z",
  },
  {
    id: "rescue-003",
    title: "2009 E-One Rescue/Pumper",
    year: 2009,
    manufacturer: "E-One",
    category: "Rescue Trucks",
    type: "Rescue",
    price: 55000,
    mileage: 78000,
    pumpGPM: 1000,
    tankGallons: 500,
    city: "Austin",
    state: "TX",
    imageUrl: "https://placehold.co/400x300/ea580c/ffffff?text=2009+E-One+Rescue",
    listingType: "buy_now",
    createdAt: "2024-01-06T10:00:00Z",
  },
];

// Default saved search - seeded on first visit for demo purposes
export const DEFAULT_SAVED_SEARCH: SavedSearch = {
  id: "saved-001",
  name: "Texas Pierce Pumpers Under $150k",
  email: "demo@example.com",
  frequency: "daily",
  status: "active",
  createdAt: "2024-01-01T12:00:00Z",
  filters: {
    category: "Fire Apparatus",
    manufacturers: ["Pierce"],
    state: "TX",
    priceMax: 150000,
  },
};

// Demo filter preset - different from saved search for clickthrough demo
export const DEMO_FILTER_PRESET = {
  filters: {
    category: "Fire Apparatus",
    manufacturers: ["E-One"],
    priceMax: 200000,
  },
  // Pre-filled values for the save modal
  suggestedName: "E-One Fire Apparatus Under $200k",
  suggestedEmail: "demo@firestation.gov",
};

// Generate a listing that matches given search filters
export function generateMatchingListing(filters: {
  category?: string;
  manufacturers?: string[];
  state?: string;
  priceMin?: number;
  priceMax?: number;
  yearMin?: number;
  yearMax?: number;
}): Listing {
  const manufacturer = filters.manufacturers?.[0] || "Pierce";
  const state = filters.state || "TX";
  const category = filters.category || "Fire Apparatus";

  // Price within range
  const minPrice = filters.priceMin || 50000;
  const maxPrice = filters.priceMax || 200000;
  const price = Math.floor(minPrice + Math.random() * (maxPrice - minPrice));

  // Year within range
  const minYear = filters.yearMin || 2010;
  const maxYear = filters.yearMax || 2022;
  const year = Math.floor(minYear + Math.random() * (maxYear - minYear));

  const cities: Record<string, string[]> = {
    TX: ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth"],
    CA: ["Los Angeles", "San Diego", "Sacramento", "San Francisco"],
    FL: ["Miami", "Tampa", "Orlando", "Jacksonville"],
    NY: ["New York", "Buffalo", "Albany", "Syracuse"],
  };
  const stateCities = cities[state] || ["Metro City"];
  const city = stateCities[Math.floor(Math.random() * stateCities.length)];

  const models: Record<string, string[]> = {
    Pierce: ["Enforcer", "Velocity", "Arrow XT", "Saber", "Dash CF"],
    "E-One": ["Typhoon", "Quest", "Cyclone II"],
    Seagrave: ["Marauder II", "Aerialscope"],
    KME: ["Predator", "Severe Service"],
  };
  const modelList = models[manufacturer] || ["Custom"];
  const model = modelList[Math.floor(Math.random() * modelList.length)];

  return {
    id: `gen-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
    title: `${year} ${manufacturer} ${model} Pumper`,
    year,
    manufacturer,
    category: category as Listing["category"],
    type: "Pumper",
    price,
    mileage: Math.floor(20000 + Math.random() * 60000),
    pumpGPM: [1250, 1500, 1750, 2000][Math.floor(Math.random() * 4)],
    tankGallons: [500, 750, 1000][Math.floor(Math.random() * 3)],
    city,
    state,
    imageUrl: `https://placehold.co/400x300/dc2626/ffffff?text=${year}+${manufacturer}`,
    listingType: "buy_now",
    createdAt: new Date().toISOString(),
  };
}

// Pre-crafted listings that match DEFAULT_SAVED_SEARCH
// These are NOT in INITIAL_LISTINGS - added when "Simulate" is clicked
export const SIMULATABLE_LISTINGS: Listing[] = [
  {
    id: "sim-001",
    title: "2016 Pierce Velocity Pumper",
    year: 2016,
    manufacturer: "Pierce",
    category: "Fire Apparatus",
    type: "Pumper",
    price: 125000,
    mileage: 38000,
    pumpGPM: 1500,
    tankGallons: 750,
    city: "San Antonio",
    state: "TX",
    imageUrl: "https://placehold.co/400x300/dc2626/ffffff?text=2016+Pierce+Velocity",
    listingType: "buy_now",
    createdAt: new Date().toISOString(),
  },
  {
    id: "sim-002",
    title: "2014 Pierce Saber Pumper",
    year: 2014,
    manufacturer: "Pierce",
    category: "Fire Apparatus",
    type: "Pumper",
    price: 89000,
    mileage: 52000,
    pumpGPM: 1250,
    tankGallons: 1000,
    city: "Fort Worth",
    state: "TX",
    imageUrl: "https://placehold.co/400x300/dc2626/ffffff?text=2014+Pierce+Saber",
    listingType: "buy_now",
    createdAt: new Date().toISOString(),
  },
  {
    id: "sim-003",
    title: "2019 Pierce Enforcer PUC Pumper",
    year: 2019,
    manufacturer: "Pierce",
    category: "Fire Apparatus",
    type: "Pumper",
    price: 148000,
    mileage: 22000,
    pumpGPM: 1500,
    tankGallons: 500,
    city: "El Paso",
    state: "TX",
    imageUrl: "https://placehold.co/400x300/dc2626/ffffff?text=2019+Pierce+Enforcer",
    listingType: "buy_now",
    createdAt: new Date().toISOString(),
  },
  {
    id: "sim-004",
    title: "2012 Pierce Dash CF Pumper",
    year: 2012,
    manufacturer: "Pierce",
    category: "Fire Apparatus",
    type: "Pumper",
    price: 72000,
    mileage: 65000,
    pumpGPM: 1250,
    tankGallons: 750,
    city: "Corpus Christi",
    state: "TX",
    imageUrl: "https://placehold.co/400x300/dc2626/ffffff?text=2012+Pierce+Dash",
    listingType: "buy_now",
    createdAt: new Date().toISOString(),
  },
];
